package protocol;

public enum Protocol {
    LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE, CREATE_USER, CREATE_USER_SUCCESS, CREATE_USER_FAILURE, DOWNLOAD,
    DOWNLOAD_SUCCESS, DOWNLOAD_FAILURE, UPLOAD, UPLOAD_SUCCESS, UPLOAD_FAILURE, LOGOFF, LOGOFF_SUCCESS, LOGOFF_FAILURE
}

