package protocol;

public enum Protocol {
    CONNECT, CONNECTION_SUCCESS, CONNECTION_FAILURE, LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE,
    DOWNLOAD, DOWNLOAD_SUCCESS, DOWNLOAD_FAILURE, UPLOAD, UPLOAD_SUCCESS, UPLOAD_FAILURE,
    LOGOFF, LOGOFF_SUCCESS, LOGOFF_FAILURE
}

